name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Debug file structure
      run: ls -al

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install

    - name: Build the project (if needed)
      run: |
        npm run build

    - name: Deploy to Netlify
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      run: |
        curl -sL https://github.com/netlify/cli/releases/download/v7.4.1/netlify-cli-linux-x64.tar.gz | tar xz
        ./netlify deploy --prod --dir=./public --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID
